project:
  type: website
  output-dir: docs

website:
  title: "Hunter Glanz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - courses.qmd
      - projects.qmd
      - interests.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

